services:
  - type: web
    name: car-dating-app
    env: python
    buildCommand: pip install -e .
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        fromDatabase:
          name: car-dating-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false

databases:
  - name: car-dating-db
    databaseName: car_dating
    user: car_dating_user
    plan: free 